export const DETAILS_REQUEST = 'DETAILS_REQUEST';
export const DETAILS_REQUEST_FAILURE = 'DETAILS_REQUEST_FAILURE';
export const DETAILS_REQUEST_SUCCESS = 'DETAILS_REQUEST_SUCCESS';
export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_REQUEST_FAILURE = 'LIST_REQUEST_FAILURE';
export const LIST_REQUEST_SUCCESS = 'LIST_REQUEST_SUCCESS';
